services:
- type: web
  name: jp7an-timing-api
  env: node
  region: frankfurt
  plan: free
  autoDeploy: true
  rootDir: apps/api
  buildCommand: |
    npm ci
    npx prisma generate --schema ../../prisma/schema.prisma
    npx prisma migrate deploy --schema ../../prisma/schema.prisma
    npm run build
  startCommand: npm start
  healthCheckPath: /health
  envVars:
  - fromGroup: jp7an-timing
  - key: NODE_ENV
    value: production

- type: web
  name: jp7an-timing-web
  env: node
  region: frankfurt
  plan: free
  autoDeploy: true
  rootDir: apps/web
  buildCommand: |
    npm ci
    npm run build
  startCommand: npm start
  envVars:
  - fromGroup: jp7an-timing
  - key: NODE_ENV
    value: production
